# Credits

This is heavily influenced or copied from https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used. If you have a cuda enabled machine, read the README.md in the root of this repo on how to use nvidia-docker.


It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [42]:
import torch

Construct a 5x3 matrix, uninitialized

In [43]:
x = torch.Tensor(5, 3)
print(x)

tensor([[1.3367e+17, 3.0757e-41, 1.4714e-43],
        [1.5414e-43, 1.6255e-43, 5.6052e-44],
        [1.6816e-43, 4.4842e-44, 5.8855e-44],
        [4.4842e-44, 1.6956e-43, 5.7453e-44],
        [4.7428e+30, 1.8064e+31, 3.8149e+03]])


Construct a randomly initialized matrix

In [44]:
x = torch.rand(5, 3)
print(x)

tensor([[0.9348, 0.9547, 0.7614],
        [0.5649, 0.5473, 0.1950],
        [0.7178, 0.6426, 0.7891],
        [0.9753, 0.0927, 0.0071],
        [0.7473, 0.7237, 0.3843]])


Get its size

In [45]:
print(x.size())

torch.Size([5, 3])


**NOTE** `torch.Size` is in fact a tuple, so it supports the same operations

In [46]:
x[1:3] = 2
print(x)

tensor([[0.9348, 0.9547, 0.7614],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.9753, 0.0927, 0.0071],
        [0.7473, 0.7237, 0.3843]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [47]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.6528, 1.2502, 1.5023],
        [2.0237, 2.8208, 2.9134],
        [2.0763, 2.5339, 2.8215],
        [1.4717, 0.7705, 0.1174],
        [1.7277, 1.6650, 0.6344]])


### 2.2 Addition: syntax 2

In [48]:
print(torch.add(x, y))

tensor([[1.6528, 1.2502, 1.5023],
        [2.0237, 2.8208, 2.9134],
        [2.0763, 2.5339, 2.8215],
        [1.4717, 0.7705, 0.1174],
        [1.7277, 1.6650, 0.6344]])


### 2.3 Addition: giving an output tensor

In [49]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.6528, 1.2502, 1.5023],
        [2.0237, 2.8208, 2.9134],
        [2.0763, 2.5339, 2.8215],
        [1.4717, 0.7705, 0.1174],
        [1.7277, 1.6650, 0.6344]])


### 2.4 Addition: in-place

adds `x`to `y`

In [50]:
y.add_(x)
print(y)

tensor([[1.6528, 1.2502, 1.5023],
        [2.0237, 2.8208, 2.9134],
        [2.0763, 2.5339, 2.8215],
        [1.4717, 0.7705, 0.1174],
        [1.7277, 1.6650, 0.6344]])


**NOTE** Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [51]:
print(x[:, 1])

tensor([0.9547, 2.0000, 2.0000, 0.0927, 0.7237])


**Read later** 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [53]:
y = torch.rand(2, 4)
x = torch.rand(4, 2)
print(x.matmul(y))

tensor([[0.6215, 0.5387, 0.4998, 0.5176],
        [1.1823, 0.8972, 0.7310, 0.9550],
        [0.9319, 0.8137, 0.7596, 0.7775],
        [1.2300, 0.9598, 0.8061, 0.9996]])


## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [54]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [55]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.

In [56]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [57]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a numpy array
3. now convert it back to a torch tensor

In [67]:
y = torch.ones(5, 2)
y = y.numpy()

In [68]:
y = torch.from_numpy(y)
y

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [70]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # this is meant as a tensor to be run on the GPU.
    # the .cuda() does this to any parameter it is applied to
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")

CUDA not available on your machine.
